/**
 * Identifiers for imports.
 *
 * - Import id: lowercase UUID v4 generated by the server.
 * - Project id of an import: `import:<uuid>`. This is the single place that defines
 *   what counts as an import, so every service can gate on `isImportProjectId()`.
 * - Eval trace session id: opaque `t001`, `t002`, ... mapped to files in manifest.json.
 *
 * Ids from clients are only ever matched against these anchored patterns; they are
 * never joined into a path before validation.
 */

import {
  IMPORT_PROJECT_PREFIX,
  isImportId,
  isImportProjectId,
  parseImportProjectId,
} from '@shared/utils/importProjectId';
import { randomUUID } from 'crypto';

export { isImportId, isImportProjectId, parseImportProjectId };

const EVAL_TRACE_ID_PATTERN = /^t\d{3,6}$/;

export function generateImportId(): string {
  return randomUUID();
}

export function buildImportProjectId(importId: string): string {
  if (!isImportId(importId)) {
    throw new Error('Invalid import id');
  }
  return `${IMPORT_PROJECT_PREFIX}${importId}`;
}

export function formatEvalTraceId(index: number): string {
  return `t${String(index + 1).padStart(3, '0')}`;
}

export function isEvalTraceId(value: unknown): value is string {
  return typeof value === 'string' && EVAL_TRACE_ID_PATTERN.test(value);
}
